# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interfaz3.ui'
#
# Created: Tue Aug  2 13:11:18 2011
#      by: PyQt4 UI code generator 4.7.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui
import sys



    
class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(602, 502)
        MainWindow.setWindowTitle("Tests ULM")
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.scrollArea = QtGui.QScrollArea(self.centralwidget)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtGui.QWidget(self.scrollArea)
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 471, 696))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_2 = QtGui.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.LayoutOpciones = QtGui.QVBoxLayout()
        self.LayoutOpciones.setObjectName("LayoutOpciones")
        self.pregunta1 = QtGui.QGroupBox(self.scrollAreaWidgetContents)
        self.pregunta1.setAccessibleDescription("None")
        self.pregunta1.setTitle("1. Texto de la Pregunta")
        self.pregunta1.setFlat(True)
        self.pregunta1.setObjectName("pregunta1")
        self.verticalLayout_9 = QtGui.QVBoxLayout(self.pregunta1)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.LayoutPregunta1 = QtGui.QVBoxLayout()
        self.LayoutPregunta1.setObjectName("LayoutPregunta1")
        self.opcion1A = QtGui.QRadioButton(self.pregunta1)
        self.opcion1A.setAccessibleDescription("None")
        self.opcion1A.setObjectName("opcion1A")
        self.LayoutPregunta1.addWidget(self.opcion1A)
        self.opcion1B = QtGui.QRadioButton(self.pregunta1)
        self.opcion1B.setAccessibleDescription("None")
        self.opcion1B.setObjectName("opcion1B")
        self.LayoutPregunta1.addWidget(self.opcion1B)
        self.opcion1C = QtGui.QRadioButton(self.pregunta1)
        self.opcion1C.setAccessibleDescription("None")
        self.opcion1C.setObjectName("opcion1C")
        self.LayoutPregunta1.addWidget(self.opcion1C)
        self.opcion1D = QtGui.QRadioButton(self.pregunta1)
        self.opcion1D.setAccessibleDescription("None")
        self.opcion1D.setObjectName("opcion1D")
        self.LayoutPregunta1.addWidget(self.opcion1D)
        self.verticalLayout_9.addLayout(self.LayoutPregunta1)
        self.LayoutOpciones.addWidget(self.pregunta1)
        self.pregunta2 = QtGui.QGroupBox(self.scrollAreaWidgetContents)
        self.pregunta2.setAccessibleDescription("None")
        self.pregunta2.setTitle("2. Texto de la pregunta")
        self.pregunta2.setFlat(True)
        self.pregunta2.setObjectName("pregunta2")
        self.verticalLayout_10 = QtGui.QVBoxLayout(self.pregunta2)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.LayoutPregunta2 = QtGui.QVBoxLayout()
        self.LayoutPregunta2.setObjectName("LayoutPregunta2")
        self.opcion2A = QtGui.QRadioButton(self.pregunta2)
        self.opcion2A.setAccessibleDescription("None")
        self.opcion2A.setObjectName("opcion2A")
        self.LayoutPregunta2.addWidget(self.opcion2A)
        self.opcion2B = QtGui.QRadioButton(self.pregunta2)
        self.opcion2B.setAccessibleDescription("None")
        self.opcion2B.setObjectName("opcion2B")
        self.LayoutPregunta2.addWidget(self.opcion2B)
        self.opcion2C = QtGui.QRadioButton(self.pregunta2)
        self.opcion2C.setAccessibleDescription("None")
        self.opcion2C.setObjectName("opcion2C")
        self.LayoutPregunta2.addWidget(self.opcion2C)
        self.opcion2D = QtGui.QRadioButton(self.pregunta2)
        self.opcion2D.setAccessibleDescription("None")
        self.opcion2D.setObjectName("opcion2D")
        self.LayoutPregunta2.addWidget(self.opcion2D)
        self.verticalLayout_10.addLayout(self.LayoutPregunta2)
        self.LayoutOpciones.addWidget(self.pregunta2)
        self.pregunta3 = QtGui.QGroupBox(self.scrollAreaWidgetContents)
        self.pregunta3.setAccessibleDescription("None")
        self.pregunta3.setTitle("3. Texto de la pregunta")
        self.pregunta3.setFlat(True)
        self.pregunta3.setObjectName("pregunta3")
        self.verticalLayout_11 = QtGui.QVBoxLayout(self.pregunta3)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.LayoutPregunta3 = QtGui.QVBoxLayout()
        self.LayoutPregunta3.setObjectName("LayoutPregunta3")
        self.opcion3A = QtGui.QRadioButton(self.pregunta3)
        self.opcion3A.setAccessibleDescription("None")
        self.opcion3A.setObjectName("opcion3A")
        self.LayoutPregunta3.addWidget(self.opcion3A)
        self.opcion3B = QtGui.QRadioButton(self.pregunta3)
        self.opcion3B.setAccessibleDescription("None")
        self.opcion3B.setObjectName("opcion3B")
        self.LayoutPregunta3.addWidget(self.opcion3B)
        self.opcion3C = QtGui.QRadioButton(self.pregunta3)
        self.opcion3C.setAccessibleDescription("None")
        self.opcion3C.setObjectName("opcion3C")
        self.LayoutPregunta3.addWidget(self.opcion3C)
        self.opcion3D = QtGui.QRadioButton(self.pregunta3)
        self.opcion3D.setAccessibleDescription("None")
        self.opcion3D.setObjectName("opcion3D")
        self.LayoutPregunta3.addWidget(self.opcion3D)
        self.verticalLayout_11.addLayout(self.LayoutPregunta3)
        self.LayoutOpciones.addWidget(self.pregunta3)
        self.pregunta4 = QtGui.QGroupBox(self.scrollAreaWidgetContents)
        self.pregunta4.setAccessibleDescription("None")
        self.pregunta4.setTitle("4. Texto de la pregunta")
        self.pregunta4.setFlat(True)
        self.pregunta4.setObjectName("pregunta4")
        self.verticalLayout_12 = QtGui.QVBoxLayout(self.pregunta4)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.LayoutPregunta4 = QtGui.QVBoxLayout()
        self.LayoutPregunta4.setObjectName("LayoutPregunta4")
        self.opcion4A = QtGui.QRadioButton(self.pregunta4)
        self.opcion4A.setAccessibleDescription("None")
        self.opcion4A.setObjectName("opcion4A")
        self.LayoutPregunta4.addWidget(self.opcion4A)
        self.opcion4B = QtGui.QRadioButton(self.pregunta4)
        self.opcion4B.setAccessibleDescription("None")
        self.opcion4B.setObjectName("opcion4B")
        self.LayoutPregunta4.addWidget(self.opcion4B)
        self.opcion4C = QtGui.QRadioButton(self.pregunta4)
        self.opcion4C.setAccessibleDescription("None")
        self.opcion4C.setObjectName("opcion4C")
        self.LayoutPregunta4.addWidget(self.opcion4C)
        self.opcion4D = QtGui.QRadioButton(self.pregunta4)
        self.opcion4D.setAccessibleDescription("None")
        self.opcion4D.setObjectName("opcion4D")
        self.LayoutPregunta4.addWidget(self.opcion4D)
        self.verticalLayout_12.addLayout(self.LayoutPregunta4)
        self.LayoutOpciones.addWidget(self.pregunta4)
        self.pregunta5 = QtGui.QGroupBox(self.scrollAreaWidgetContents)
        self.pregunta5.setAccessibleDescription("None")
        self.pregunta5.setTitle("5. Texto de la pregunta")
        self.pregunta5.setFlat(True)
        self.pregunta5.setObjectName("pregunta5")
        self.verticalLayout_13 = QtGui.QVBoxLayout(self.pregunta5)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.LayoutPregunta5 = QtGui.QVBoxLayout()
        self.LayoutPregunta5.setObjectName("LayoutPregunta5")
        self.opcion5A = QtGui.QRadioButton(self.pregunta5)
        self.opcion5A.setAccessibleDescription("None")
        self.opcion5A.setObjectName("opcion5A")
        self.LayoutPregunta5.addWidget(self.opcion5A)
        self.opcion5B = QtGui.QRadioButton(self.pregunta5)
        self.opcion5B.setAccessibleDescription("None")
        self.opcion5B.setObjectName("opcion5B")
        self.LayoutPregunta5.addWidget(self.opcion5B)
        self.opcion5C = QtGui.QRadioButton(self.pregunta5)
        self.opcion5C.setAccessibleDescription("None")
        self.opcion5C.setObjectName("opcion5C")
        self.LayoutPregunta5.addWidget(self.opcion5C)
        self.opcion5D = QtGui.QRadioButton(self.pregunta5)
        self.opcion5D.setAccessibleDescription("None")
        self.opcion5D.setObjectName("opcion5D")
        self.LayoutPregunta5.addWidget(self.opcion5D)
        self.verticalLayout_13.addLayout(self.LayoutPregunta5)
        self.LayoutOpciones.addWidget(self.pregunta5)
        self.gridLayout_2.addLayout(self.LayoutOpciones, 0, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout.addWidget(self.scrollArea, 0, 0, 1, 1)
        self.LayoutBotones = QtGui.QVBoxLayout()
        self.LayoutBotones.setObjectName("LayoutBotones")
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.LayoutBotones.addItem(spacerItem)
        self.botonSiguientes = QtGui.QPushButton(self.centralwidget)
        self.botonSiguientes.setObjectName("botonSiguientes")
        self.LayoutBotones.addWidget(self.botonSiguientes)
        self.botonAnteriores = QtGui.QPushButton(self.centralwidget)
        self.botonAnteriores.setObjectName("botonAnteriores")
        self.LayoutBotones.addWidget(self.botonAnteriores)
        self.botonCorregir = QtGui.QPushButton(self.centralwidget)
        self.botonCorregir.setObjectName("botonCorregir")
        self.LayoutBotones.addWidget(self.botonCorregir)
        self.gridLayout.addLayout(self.LayoutBotones, 0, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 602, 20))
        self.menubar.setObjectName("menubar")
        self.menuNuevo = QtGui.QMenu(self.menubar)
        self.menuNuevo.setObjectName("menuNuevo")
        self.menuEstadisticas = QtGui.QMenu(self.menubar)
        self.menuEstadisticas.setObjectName("menuEstadisticas")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionTests = QtGui.QAction(MainWindow)
        self.actionTests.setObjectName("actionTests")
        self.action20_preguntas = QtGui.QAction(MainWindow)
        self.action20_preguntas.setObjectName("action20_preguntas")
        self.action50_preguntas = QtGui.QAction(MainWindow)
        self.action50_preguntas.setObjectName("action50_preguntas")
        self.action100_preguntas = QtGui.QAction(MainWindow)
        self.action100_preguntas.setObjectName("action100_preguntas")
        self.menuNuevo.addAction(self.actionTests)
        self.menuNuevo.addAction(self.action20_preguntas)
        self.menuNuevo.addAction(self.action50_preguntas)
        self.menuNuevo.addAction(self.action100_preguntas)
        self.menubar.addAction(self.menuNuevo.menuAction())
        self.menubar.addAction(self.menuEstadisticas.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        self.opcion1A.setText(QtGui.QApplication.translate("MainWindow", "Texto Opción A", None, QtGui.QApplication.UnicodeUTF8))
        self.opcion1B.setText(QtGui.QApplication.translate("MainWindow", "Texto Opción B", None, QtGui.QApplication.UnicodeUTF8))
        self.opcion1C.setText(QtGui.QApplication.translate("MainWindow", "Texto Opción C", None, QtGui.QApplication.UnicodeUTF8))
        self.opcion1D.setText(QtGui.QApplication.translate("MainWindow", "Texto Opción D", None, QtGui.QApplication.UnicodeUTF8))
        self.opcion2A.setText(QtGui.QApplication.translate("MainWindow", "Texto Opción A", None, QtGui.QApplication.UnicodeUTF8))
        self.opcion2B.setText(QtGui.QApplication.translate("MainWindow", "Texto Opción B", None, QtGui.QApplication.UnicodeUTF8))
        self.opcion2C.setText(QtGui.QApplication.translate("MainWindow", "Texto Opción C", None, QtGui.QApplication.UnicodeUTF8))
        self.opcion2D.setText(QtGui.QApplication.translate("MainWindow", "Texto Opción D", None, QtGui.QApplication.UnicodeUTF8))
        self.opcion3A.setText(QtGui.QApplication.translate("MainWindow", "Texto Opción A", None, QtGui.QApplication.UnicodeUTF8))
        self.opcion3B.setText(QtGui.QApplication.translate("MainWindow", "Texto Opción B", None, QtGui.QApplication.UnicodeUTF8))
        self.opcion3C.setText(QtGui.QApplication.translate("MainWindow", "Texto Opción C", None, QtGui.QApplication.UnicodeUTF8))
        self.opcion3D.setText(QtGui.QApplication.translate("MainWindow", "Texto Opción D", None, QtGui.QApplication.UnicodeUTF8))
        self.opcion4A.setText(QtGui.QApplication.translate("MainWindow", "Texto Opción A", None, QtGui.QApplication.UnicodeUTF8))
        self.opcion4B.setText(QtGui.QApplication.translate("MainWindow", "Texto Opción B", None, QtGui.QApplication.UnicodeUTF8))
        self.opcion4C.setText(QtGui.QApplication.translate("MainWindow", "Texto Opción C", None, QtGui.QApplication.UnicodeUTF8))
        self.opcion4D.setText(QtGui.QApplication.translate("MainWindow", "Texto Opción D", None, QtGui.QApplication.UnicodeUTF8))
        self.opcion5A.setText(QtGui.QApplication.translate("MainWindow", "Texto Opción A", None, QtGui.QApplication.UnicodeUTF8))
        self.opcion5B.setText(QtGui.QApplication.translate("MainWindow", "Texto Opción B", None, QtGui.QApplication.UnicodeUTF8))
        self.opcion5C.setText(QtGui.QApplication.translate("MainWindow", "Texto Opción C", None, QtGui.QApplication.UnicodeUTF8))
        self.opcion5D.setText(QtGui.QApplication.translate("MainWindow", "Texto Opción D", None, QtGui.QApplication.UnicodeUTF8))
        self.botonSiguientes.setText(QtGui.QApplication.translate("MainWindow", "Siguientes >>", None, QtGui.QApplication.UnicodeUTF8))
        self.botonAnteriores.setText(QtGui.QApplication.translate("MainWindow", "Anteriores <<", None, QtGui.QApplication.UnicodeUTF8))
        self.botonCorregir.setText(QtGui.QApplication.translate("MainWindow", "Corregir", None, QtGui.QApplication.UnicodeUTF8))
        self.menuNuevo.setTitle(QtGui.QApplication.translate("MainWindow", "Nuevo", None, QtGui.QApplication.UnicodeUTF8))
        self.menuEstadisticas.setTitle(QtGui.QApplication.translate("MainWindow", "Estadísticas", None, QtGui.QApplication.UnicodeUTF8))
        self.actionTests.setText(QtGui.QApplication.translate("MainWindow", "10 preguntas", None, QtGui.QApplication.UnicodeUTF8))
        self.action20_preguntas.setText(QtGui.QApplication.translate("MainWindow", "20 preguntas", None, QtGui.QApplication.UnicodeUTF8))
        self.action50_preguntas.setText(QtGui.QApplication.translate("MainWindow", "50 preguntas", None, QtGui.QApplication.UnicodeUTF8))
        self.action100_preguntas.setText(QtGui.QApplication.translate("MainWindow", "100 preguntas", None, QtGui.QApplication.UnicodeUTF8))